### ISSUE TITLE
Add support for specifying path to log file

### ISSUE THREAD

**Issue by neilenns** [node-3d/segfault-raub#14]
I'm trying to use this in an electron-builder app to catch a crash users are seeing, however I can't figure out where the segfault.log file is supposed to exist in order for this library to log the crash to it.

It would be wonderful if I could specify the exact path to the log file with something like `setLog(pathToLogFile)` so I can specifically put the log file in a known location.

**Comment by raub** [comment]
Hello. The log file should be created by you in "the working directory", because the addon simply uses [the file name without paths](https://github.com/node-3d/segfault-raub/blob/master/src/cpp/segfault-handler.cpp#L214).

I will try to add the ability to change the log file path so that the existing behavior remains default.

**Comment by raub** [comment]
Published as [3.0.1](https://www.npmjs.com/package/segfault-raub). Added to [readme](https://github.com/node-3d/segfault-raub?tab=readme-ov-file#segfault-handler-for-nodejs). Also, [d.ts link](https://github.com/node-3d/segfault-raub/blob/3.0.1/index.d.ts#L38)

**Comment by neilenns** [comment]
Awesome thank you, I'll give it a try later today!

**Comment by neilenns** [comment]
I gave this a try on Windows and didn't have any luck getting anything to write to the log file. I must be missing something. Here's the sample:

```typescript
import segfault from 'segfault-raub';
segfault.setLogPath('d:\\git\\segfault.txt');
segfault.causeSegfault();
```

I created the file on disk first:

![image](https://github.com/user-attachments/assets/e5cace14-8093-435f-8014-7cfe6355f989)

Then I ran the app. It does segfault but nothing gets added to the log file. I also tried specifying the path as `d:/git/segfault.txt` but that didn't make a difference.

**Comment by raub** [comment]
Hello, did you try `'d:/git/segfault.txt'` instead of `'d:\\git\\segfault.txt'`?

Also, [this test](https://github.com/node-3d/segfault-raub/blob/master/test/logging.test.js#L73) confirms that it is at least possible to write the custom log, but I think I also [struggled with slashes](https://github.com/node-3d/segfault-raub/blob/master/test/logging.test.js#L11) at some point.

---

Well, maybe, I need to "normalize" the slashes in `setLogPath` automatically...

**Comment by neilenns** [comment]
I did try both ways :(

**Comment by raub** [comment]
I added [this example](https://github.com/node-3d/segfault-raub/blob/master/examples/custom.js), which works on my Windows PC. Please try running it and see if the same works on yours.
